# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef2b488575c1946b3ca90d53ebfe4c75bd2bfa53e11637b9cf1e6d687e9592afc3ce7e07aa0e77cd905379932ab22b89c7fa956ebfc66e2d599760bc81766c1

test:
  secret_key_base: fc4a03f5b994f98b39d2df5324df0f6b7928008d33e6b47efe3dacf7678e08a1e097014af9a05eb4e7c65951ec5325abc68e71ce1af3efbe2064357353762763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
